# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: com.traveladvisor/gatewayserver:1.0.0-SNAPSHOT
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

appname_enabled: true
postgres_enabled: false
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
