server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/configs"
          # 애플리케이션이 시작될 때 Git 저장소에서 config 설정 파일들을 클론하고 적용합니다.
        git:
          uri: "https://github.com/SunhyeokChoe/traveladvisor-kubernetes-msa.git"
          search-paths: "infrastructure/configs/**"
          default-label: main
          force-pull: true
          clone-on-start: true
          timeout: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "9A0RO1RT2PP3S9WEOLLE32SDGG53JE5KKE0O"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
