INSERT INTO event.events (event_name,
                          event_description,
                          action_type,
                          reward_type,
                          reward_value,
                          start_date,
                          end_date,
                          status,
                          created_by,
                          modified_by)
VALUES ('회원가입 시 포인트 지급 이벤트',
        '신규 회원가입 시 1,000,000 포인트 지급',
        'SIGNUP',
        'POINT',
        '1000000',
        NOW(),
        '2090-12-31 23:59:59+00',
        'ACTIVE',
        'ADMIN',
        NULL);

INSERT INTO event.events (event_name,
                          event_description,
                          action_type,
                          reward_type,
                          reward_value,
                          start_date,
                          end_date,
                          status,
                          created_by,
                          modified_by)
VALUES ('추천인 추천 시 10% 할인 쿠폰 지급 이벤트',
        '추천인 추천 시 10% 할인 쿠폰을 지급합니다.',
        'REFERRAL',
        'VOUCHER',
        '10% 할인 쿠폰',
        NOW(),
        '2090-12-31 23:59:59+00',
        'ACTIVE',
        'ADMIN',
        NULL);
