build:
  version: "1.0"
  description: "Batch Service Configuration for Distributed Environment"
  created_by: "SunhyeokChoe"
  created_at: "2024-12-21"
  updated_at: "2024-12-21"

batch:
  message: "[PROFILE: PROD] Batch Service API 입니다."
  environment:
    stage: "prod"
    region: "AP-NORTHEAST-1"
  contacts:
    name: "SunhyeokChoe - Developer"
    email: "sunhyeokchoe@gmail.com"
    github: "https://github.com/sunhyeokchoe"
  phones:
    - "+82 000-0000-0000"

  metadata:
    service_owner: "Batch Processing Team"
    sla: "99.9%"
    service_tier: "Tier-1"

  performance:
    max_threads: 16
    max_memory_mb: 1024
    timeout_ms: 30000

  logging:
    level: "INFO"
    log_rotation: "7 days"
    log_storage_path: "/var/logs/batch-service"
